runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: grpcio
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /data
  static_dir: data
- url: /.*
  script: main.app